name: Miri test

on: [push, pull_request]

jobs:
  build:
    name: Test with Miri
    runs-on: ${{ matrix.os }}
    # We want to run on external PRs, but not on internal ones as push automatically builds
    # H/T: https://github.com/Dart-Code/Dart-Code/commit/612732d5879730608baa9622bf7f5e5b7b51ae65
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'amazon-ion/ion-rust'
    strategy:
      matrix:
        # See https://github.com/amazon-ion/ion-rust/issues/353
        os: [ubuntu-latest, windows-latest, macos-latest]
        # build and test for experimental features with miri
        features: ['experimental']
    permissions:
      checks: write

    steps:
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: miri
          override: true
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test serde --features "experimental"
